subgraphs:
  reference:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../../book-store/reference/schema.graphql
  products:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ../../book-store/products/schema.graphql
  reviews:
    routing_url: http://localhost:4004/graphql
    schema:
      file: ../../book-store/reviews/schema.graphql
